### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by dbrgn** [fontobene/fontobene-qt5#12]
With qt6 released, the "fontobene-qt5" name is a bit awkward. Should we rename it to something version-independent?

Proposal: Rename this library to `fontobene-qt`. GitHub redirects the old name, so existing submodules should not break.

Steps:

- [x] Rename repo
- [x] Update README and all packaging files (CMakeLists.txt and qmake project files)
- [ ] Update CHANGELOG
- [x] Update dependent software (LibrePCB)
- [x] Notify packagers in Arch Linux, OpenSuse and FreeBSD

Anything else?

**Comment by ubruhin** [comment]
Generally I like the idea. However, I wonder if this is the best solution.

In the end, we have to decide between two options:
- Keeping the library compatible with both, Qt5 and Qt6. Then the renaming to `fontobene-qt` probably makes sense.
- Having separate libraries for Qt5 and Qt6 (i.e. `fontobene-qt5` and `fontobene-qt6`). Then we should leave this repository as-is and create a new one.

At the moment I don't know how hard it is to support both Qt5 and Qt6 at the same time (without lots of `#ifdef`, deprecation warnings etc.). Maybe we should try this first before deciding how to proceed with this topic?

**Comment by dbrgn** [comment]
Yeah. I opened this issue mainly because I thought we'll have a breaking change in #11. But since we didn't merge that one, we can put this on hold until we need/provide Qt6 compatibility.

**Comment by ubruhin** [comment]
This gets more important due to https://github.com/LibrePCB/LibrePCB/issues/1052.

Somehow from the Fontobene developers point of view I'd simply create a new repository `fontobene-qt6` to keep things simple and to also get rid of `qmake` without making a breaking change - this repository could then just slowly die as Qt5 is no longer needed for long-term. And hopefully package maintainers follow this naming to also keep it clean & simple for users (no renaming). For Qt libraries it's very common anyway to distinguish between the major versions (see also Qt4 vs. Qt5).

However, from the LibrePCB developers point of view that's a bit cumbersome since we include the library as a submodule - I don't want to add *both* repositories. As a pragmatic workaround we could still (maybe inofficially) keep the `fontobene-qt6` library compatible with Qt5 to allow including only `fontobene-qt6` in LibrePCB :see_no_evil: I quickly verified in f3439ccfc701411b9b392caeae21c3cfe3b045a6 that this seems to be very easy.

EDIT: Since keeping it compatible with both Qt versions is so simple, I now still wonder whether renaming makes more sense :thinking:

**Comment by dbrgn** [comment]
If it's so easy to support both versions, I'd go with a rename.

**Comment by ubruhin** [comment]
Arghh although Qt6 compatibility is not a big thing for this library, the rename will break things for users:

- The include path will change (currently `fontobene-qt5`)
- The CMake library names will change (currently `fontobene_qt5` and `FontoBene::FontoBeneQt5`)

Although the CMake library names could be kept backwards compatible, the include path is still a big problem.

So in fact, for users (and packagers) a rename basically means it will be a completely different library. So maybe we should take it that way too, i.e. creating a new library:

1. Add a deprecation note to `README.md` and archive this repository.
2. Create a new repository `fontobene-qt` and populate it with a copy of this repository, except:
  - Get rid of all qmake things (no qmake support anymore, even for Qt5)
  - Bump the version number (we could start over with 0.1.0, but to avoid confusion I'd rather go with 1.0.0)
  - I'm not sure about the pkg-config file. It specifies `Qt5Core` as a dependency, but for a Qt5/Qt6 compatible library we don't know whether to depend on `Qt5Core` or `Qt6Core`. Maybe we should add separate files `fontobene-qt5.pc.example` and `fontobene-qt6.pc.example` so the user has the choice with which Qt version he wants to use this library. However, for distributions which already deploy a `fontobene-qt5.pc` ([like Arch](https://archlinux.org/packages/extra/any/fontobene-qt5/files/)), it would lead to a conflict :sob: Alternatively we could choose the uglier naming `fontobene-qt-qt5.pc.example` and `fontobene-qt-qt6.pc.example` :thinking: 

Maybe I am overthinking about this, but I really don't want to mess up packaging or creating other troubles. Any opinions about the proposed steps @dbrgn?

EDIT: I think I'll start with creating a new repository to see how it would work. We could still decide later and delete the new repository if it turns out to be not needed.

**Comment by ubruhin** [comment]
For the record, I've notified all package maintainers of the 3 distributions listed in https://github.com/fontobene/fontobene-qt5/issues/12#issue-777308573.

**Comment by lgbaldoni** [comment]
@ubruhin LGTM
