### ISSUE TITLE
fontobene-qt5 development package not found

### ISSUE THREAD

**Issue by FFY00** [fontobene/fontobene-qt5#7]
While preparing an arch package for LibrePCB I run into the following:

```
Project ERROR: fontobene-qt5 development package not found
```

I have latest release of fontobene-qt5. This is a tree of the files installed by the package:

```
usr
 ├─include
 │  └─fontobene-qt5
 │     ├─exception.h
 │     ├─font.h
 │     ├─fontobene.h
 │     ├─glyph.h
 │     ├─glyphlist.h
 │     ├─glyphlistaccessor.h
 │     ├─glyphlistcache.h
 │     ├─header.h
 │     └─helpers.h
 └─share
    └─licenses
       └─fontobene-qt5
          ├─LICENSE-APACHE
          └─LICENSE-MIT
```

**Comment by dbrgn** [comment]
Hi. Looks like the pkg-config file is missing. Check out the AUR-Package: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fontobene-qt5

**Comment by FFY00** [comment]
pkg-config files are generally installed by the build system. I will manually add it though.

**Comment by rnestler** [comment]
> pkg-config files are generally installed by the build system.

We should probably do that. I guess this shouldn't be to hard with qmake?

**Comment by FFY00** [comment]
I am not really a qmake user but should be pretty easy, as shown in the 2nd answer here https://stackoverflow.com/questions/6794710/qt-qmake-generating-pkgconfig-for-a-project.

**Comment by dbrgn** [comment]
> We should probably do that. I guess this shouldn't be to hard with qmake?

I spent about 2-3 hours trying to get it to work. fontobene-qt5 is a headers-only library. We basically only use qmake to get "make install" to work (with all the install path detection etc). An install script can also just copy the headers to the appropriate location if it prefers to do so.

As soon as you enable package-config creation in qmake, it starts building shared libraries when doing "make install". I have no idea what those contain, but they are definitely not needed.

We could provide a ready-made pkg-config file, but that won't work in all cases since different distros use different header file locations. Thus I figured that leaving that up to the packager is probably the best choice.

**Comment by dbrgn** [comment]
I'll close this for now. If someone figures out how to get qmake to create that pkg-config file without also creating empty shared libraries, a PR would be most welcome :slightly_smiling_face:

**Comment by FFY00** [comment]
You can install the file directly, instead of having qmake generating it.

**Comment by dbrgn** [comment]
> You can install the file directly, instead of having qmake generating it.

Sure, but qmake can determine the proper includedir path. I suspect that just hardcoding `/usr/include` won't work on all platforms. I think it's probably better not to install a pkg-config file by default than to install one that may be wrong. A packager usually knows better what the proper pkg-config file should look like.

We could include the pkg-config file as an example in the repo though.

**Comment by dbrgn** [comment]
On second thought, replacing qmake with a custom makefile might be the better/simpler solution, even if it doesn't cover all edge cases.

**Comment by dbrgn** [comment]
> On second thought, replacing qmake with a custom makefile might be the better/simpler solution, even if it doesn't cover all edge cases.

I forgot that the project includes a testsuite that's also compiled by qmake. I'll just add an example pkg-config file.
